apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namePrefix: dev-

labels:
  - pairs:
      environment: dev

replicas:
  - name: app-deployment
    count: 1
